---

default_language_version:
  # This should be set to the lowest Python version that we support.
  python: python3.10

repos:

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --strict

  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.3
    hooks:

      # Equivalent to running `poetry check --lock`.
      # This checks that:
      # 1. the Poetry content of the `pyproject.toml` file is valid;
      # 2. there is a `poetry.lock` file;
      # 3. the content of `poetry.lock` is in sync
      #    with the content of `pyproject.toml`.
      - id: poetry-check
        args:
          - --lock

      # Equivalent to running `poetry lock --no-update`.
      # This syncs the `poetry.lock` file with the content
      # of the `pyproject.toml` file.
      # This hook fails if it results in modifying `poetry.lock`.
      - id: poetry-lock
        args:
          - --no-update

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        name: Autoflake
        args:
          - --expand-star-imports
          - --ignore-init-module-imports
          - --in-place
          - --remove-duplicate-keys
          - --ignore-pass-after-docstring

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        name: Black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-merge-conflict
        # exclude files where underlines are
        # not distinguishable from merge conflicts
        exclude: /README\.rst$|^docs/.*\.rst$
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
        exclude: ^.drone\.yml|meta.yaml
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        name: Flake8
        exclude: (grpc/)
