modules_path: argussight.core.video_processes

worker_classes:
  test: 
    location: vprocess.Test
    accessible: True
  flow_detection: 
    location: optical_flow_detection.OpticalFlowDetection
    accessible: True
  stream_buffer: 
    location: stream_buffer.StreamBuffer
    accessible: False
  video_recorder:
    location: video_recorder.Recorder
    accessible: False

processes:
  - name: "initial test"
    type: test
    args: []
  - name: "Saver"
    type: stream_buffer
    args: [200, logs]
  - name: "Recorder"
    type: video_recorder
    args: [logs/recordings, temp]