---

modules_path: argussight.core.video_processes

worker_classes:
  test:
    location: vprocess.Test
    accessible: true
  flow_detection:
    location: detection_algorithms.optical_flow_detection.OpticalFlowDetection
    accessible: true
  stream_buffer:
    location: savers.stream_buffer.StreamBuffer
    accessible: false
  video_recorder:
    location: savers.video_recorder.Recorder
    accessible: false

processes:
  - name: "initial test"
    type: test
    args: []
  - name: "Saver"
    type: stream_buffer
    args: [200, logs]
  - name: "Recorder"
    type: video_recorder
    args: [logs/recordings, temp]
